[
	{
		"_id": "1",
		"title": "Test Event",
		"date": "29-01-2022",
		"location": "",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis ullamcorper sapien, vel tempor massa lacinia at. Nunc congue diam nunc, eget rutrum nunc lacinia id. Mauris interdum euismod erat, sit amet condimentum ex tempor eget. Curabitur ornare nisl felis. Duis scelerisque, orci vitae auctor gravida, lorem libero mattis nunc, sed hendrerit tortor diam non nulla. Vestibulum ut hendrerit tortor, sit amet tincidunt urna. Phasellus elit tellus, ultrices quis massa vitae, iaculis scelerisque augue. Maecenas a leo vel mauris volutpat malesuada. Aliquam eu pellentesque neque. Nullam ac ornare velit. Aenean cursus ultrices tortor, et auctor leo euismod id. Sed euismod est eros, at convallis tortor tincidunt vitae. Nullam a neque tortor. Suspendisse turpis libero, placerat scelerisque ante sed, dapibus consectetur est.",
		"organiser": "Edvin Pohto",
		"tags": ["Surf", "Summer"],
		"privacy": "",
		"admission": "£2",
		"duration": "",
		"attendees": "12",
	},
	{
		"_id": "2",
		"title": "Second Event",
		"date": "25-01-2022",
		"location": "",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis ullamcorper sapien, vel tempor massa lacinia at. Nunc congue diam nunc, eget rutrum nunc lacinia id. Mauris interdum euismod erat, sit amet condimentum ex tempor eget. Curabitur ornare nisl felis. Duis scelerisque, orci vitae auctor gravida, lorem libero mattis nunc, sed hendrerit tortor diam non nulla. Vestibulum ut hendrerit tortor, sit amet tincidunt urna. Phasellus elit tellus, ultrices quis massa vitae, iaculis scelerisque augue. Maecenas a leo vel mauris volutpat malesuada. Aliquam eu pellentesque neque. Nullam ac ornare velit. Aenean cursus ultrices tortor, et auctor leo euismod id. Sed euismod est eros, at convallis tortor tincidunt vitae. Nullam a neque tortor. Suspendisse turpis libero, placerat scelerisque ante sed, dapibus consectetur est.",
		"organiser": "Edvin Pohto",
		"tags": ["Football"],
		"privacy": "",
		"admission": "Free",
		"duration": "",
		"attendees": "10",
	},
	{
		"_id": "3",
		"title": "Third Event",
		"date": "20-01-2022",
		"location": "",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis ullamcorper sapien, vel tempor massa lacinia at. Nunc congue diam nunc, eget rutrum nunc lacinia id. Mauris interdum euismod erat, sit amet condimentum ex tempor eget. Curabitur ornare nisl felis. Duis scelerisque, orci vitae auctor gravida, lorem libero mattis nunc, sed hendrerit tortor diam non nulla. Vestibulum ut hendrerit tortor, sit amet tincidunt urna. Phasellus elit tellus, ultrices quis massa vitae, iaculis scelerisque augue. Maecenas a leo vel mauris volutpat malesuada. Aliquam eu pellentesque neque. Nullam ac ornare velit. Aenean cursus ultrices tortor, et auctor leo euismod id. Sed euismod est eros, at convallis tortor tincidunt vitae. Nullam a neque tortor. Suspendisse turpis libero, placerat scelerisque ante sed, dapibus consectetur est.",
		"organiser": "Edvin Pohto",
		"tags": [],
		"privacy": "",
		"admission": "£15",
		"duration": "",
		"attendees": "20",
	},
	{
		"_id": "4",
		"title": "Test Event",
		"date": "29-01-2022",
		"location": "",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis ullamcorper sapien, vel tempor massa lacinia at. Nunc congue diam nunc, eget rutrum nunc lacinia id. Mauris interdum euismod erat, sit amet condimentum ex tempor eget. Curabitur ornare nisl felis. Duis scelerisque, orci vitae auctor gravida, lorem libero mattis nunc, sed hendrerit tortor diam non nulla. Vestibulum ut hendrerit tortor, sit amet tincidunt urna. Phasellus elit tellus, ultrices quis massa vitae, iaculis scelerisque augue. Maecenas a leo vel mauris volutpat malesuada. Aliquam eu pellentesque neque. Nullam ac ornare velit. Aenean cursus ultrices tortor, et auctor leo euismod id. Sed euismod est eros, at convallis tortor tincidunt vitae. Nullam a neque tortor. Suspendisse turpis libero, placerat scelerisque ante sed, dapibus consectetur est.",
		"organiser": "Edvin Pohto",
		"tags": ["Surf", "Summer"],
		"privacy": "",
		"admission": "£2",
		"duration": "",
		"attendees": "12",
	},
	{
		"_id": "5",
		"title": "Test Event",
		"date": "29-01-2022",
		"location": "",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis ullamcorper sapien, vel tempor massa lacinia at. Nunc congue diam nunc, eget rutrum nunc lacinia id. Mauris interdum euismod erat, sit amet condimentum ex tempor eget. Curabitur ornare nisl felis. Duis scelerisque, orci vitae auctor gravida, lorem libero mattis nunc, sed hendrerit tortor diam non nulla. Vestibulum ut hendrerit tortor, sit amet tincidunt urna. Phasellus elit tellus, ultrices quis massa vitae, iaculis scelerisque augue. Maecenas a leo vel mauris volutpat malesuada. Aliquam eu pellentesque neque. Nullam ac ornare velit. Aenean cursus ultrices tortor, et auctor leo euismod id. Sed euismod est eros, at convallis tortor tincidunt vitae. Nullam a neque tortor. Suspendisse turpis libero, placerat scelerisque ante sed, dapibus consectetur est.",
		"organiser": "Edvin Pohto",
		"tags": ["Surf", "Summer"],
		"privacy": "",
		"admission": "£2",
		"duration": "",
		"attendees": "12",
	},
	{
		"_id": "6",
		"title": "Test Event",
		"date": "29-01-2022",
		"location": "",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In mollis ullamcorper sapien, vel tempor massa lacinia at. Nunc congue diam nunc, eget rutrum nunc lacinia id. Mauris interdum euismod erat, sit amet condimentum ex tempor eget. Curabitur ornare nisl felis. Duis scelerisque, orci vitae auctor gravida, lorem libero mattis nunc, sed hendrerit tortor diam non nulla. Vestibulum ut hendrerit tortor, sit amet tincidunt urna. Phasellus elit tellus, ultrices quis massa vitae, iaculis scelerisque augue. Maecenas a leo vel mauris volutpat malesuada. Aliquam eu pellentesque neque. Nullam ac ornare velit. Aenean cursus ultrices tortor, et auctor leo euismod id. Sed euismod est eros, at convallis tortor tincidunt vitae. Nullam a neque tortor. Suspendisse turpis libero, placerat scelerisque ante sed, dapibus consectetur est.",
		"organiser": "Edvin Pohto",
		"tags": ["Surf", "Summer"],
		"privacy": "",
		"admission": "£2",
		"duration": "",
		"attendees": "12",
	},
]